services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: backend
    env_file: ./.env
    environment:
      - BACKEND_PORT=${BACKEND_PORT}
      - BACKEND_BEARER=${BACKEND_BEARER}
      - GMAPS_SERVER_KEY=${GMAPS_SERVER_KEY}
      - GMAPS_EMBED_KEY=${GMAPS_EMBED_KEY}
      - FRONTEND_ORIGIN=http://localhost:${FRONTEND_PORT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "${BACKEND_PORT}:8000"
    restart: unless-stopped

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: frontend
    environment:
      - VITE_BACKEND_URL=http://localhost:8000
      - VITE_BACKEND_BEARER=${BACKEND_BEARER}
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT}:80"
    restart: unless-stopped

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
    ports:
      - "3000:8080"
    restart: unless-stopped

  ollama:
    image: ollama/ollama:0.3.14
    platform: linux/arm64 # for Mac Apple Silicon (M1/M2/M3),
    ports:
      - "${OLLAMA_PORT}:11434"
    volumes:
      - ollama_models:/root/.ollama
    restart: unless-stopped

volumes:
  ollama_models:
